### PR TITLE
Match file structure to kickoff-base outline

### PR DESCRIPTION
**Pull request by mfouquet**
This PR matches the file structure outlined in kickoff-base based on the comments and discussion. Not many files were moved, but a decent amount were created by separating out the mixins/variables. I also stubbed out via comment blocks everything listed in the doc as well so it's easier to see at a glance what we've completed and such.

### CODE REVIEW

**Comment by mfouquet** [comment]
Yeah, I can see how that makes sense. Can't you say the same about the mixins though? Since these are colors based, shouldn't they fit more with the colors variables? I can see how it'd be more clear to name them based on what the functions do though.

Where should we draw the line on this one guys? @gcstaublin @nick-adams

**Comment by gcstaublin** [comment]
`Media` seems nebulous. Cards, seem like they would go into `cards` or when we add the variant of avatars that are the two letter initials, vs. the image avatars are those still media?

Media is such a large category, separating those out is better for clarity of purpose, in my opinion.

Same with lists. Why is that relegated to `Type`, but tables get their own file.

**Comment by gcstaublin** [comment]
Are you asking should the functions reside in the variable file itself? Or if the naming should be a 1-1 match?

For the button mixin, I probably would separate all those mixins into their own files for sake of clarity.

**Comment by nick-adams** [comment]
What if we do this...

What if we start with the broader groups, and then pull things out as we feel it makes more sense. So cards can come out of media if it makes sense once cards are built. Or avatars. Etc.

To me it makes more sense to start broader and extract as needed. What we have, in my opinion, is a solid modularized foundation to work from. It can evolve into even more specialized modules as needed.

This goes for mixins, functions, and elements.

For example, we can start with a single button mixin, if that proves to be too broad and needs to be extracted out, then so be it. But it probably also means the the button element itself is too broad and should be split up. We should make each decision in context of the rest of the library to keep the taxonomy understandable. 

The key word in all of this, is this is where we _start_. If we need to refine we can. This is step one to get us moving forward.

**Comment by nick-adams** [comment]
As far as variables and mixin _naming_ goes though, in my opinion it should match the element it relates to. _button.scss across the board. I need to change a variable that impacts how a button is built or look, I know where to go.

I think that should all be 1:1.

Functions can be the exception in some cases, especially if they don't directly relate to a specific element. But at the same time, just like I said above, we can start broad and extract/specialize as we find it necessary. It a bunch of color related functions are in a functions file called _colors.scss, but it eventually seems theyd make more sense extracted out into their own functions, that takes 2 seconds to do, and in no way impacts the ability to write those functions. The only thing it does is require us to add more files and import statements.

**Comment by gcstaublin** [comment]
As an author, I should have to look through files to figure out where cards go. It makes so much more sense to create a file called `_cards.scss` and write that css that creates that element. After we create elements, we look for sensible groupings and tighten from there.

**Comment by nick-adams** [comment]
A different path to the same goal then. Fine with me. 

Let's call this resolved and go that direction. This PR need to be amended to match this approach? Or do we just close it. This was something in this PR about removing things (or at least clearly defining them as components in a component directory and tabling their work for now) that didn't belong in kickoff-base, which I still think is valid.

**Comment by mfouquet** [comment]
I still think we should keep the mixins variables as 1-1 with the elements files. Otherwise, I'm down with amending the rest of the PR to match above.

To clarify: We're saying split out media - > avatars and cards.

Also RE: lists, we got rid of lists because we said in the google doc that those content lists make more sense as micro layouts. The numbered or unordered lists would live in type since those are more type related.

What else?

**Comment by mfouquet** [comment]
So I did a shitty job of summarizing in that last comment. Here is a better job:

No changes in this branch re: `variables`, `mixins`, and `functions` filenames matching their `elements` filenames.

We separate out the following:
-Media.scss (leave video/image in place for now)
   |_Avatars.scss
   |_Cards.scss
-Lists.scss
   |_MOVE-Micro-layout.scss (move content lists here since they are micro-layouts)
   |_REMOVE-Type.scss (remove ol/ul lists from here since they should have their own category like tables. They now live in Lists.scss)

I feel like I'm missing something - is that it?

**Comment by gcstaublin** [comment]
I don't understand what a `content list` is.

We're removing the entire `type.scss` file?

**Comment by mfouquet** [comment]
Content lists are things like the list of schedule entries on the Schedule page or list of exchanges on the Exchanges page.

Not removing the entire `type.scss` file, just removing the ol/ul elements from it and putting them in their own `lists.scss` file per the discussion above.

**Comment by gcstaublin** [comment]
2015-11-18 03 41 10 pm

That's what a micro layout accomplishes. Is that what you're describing?

**Comment by mfouquet** [comment]
Yep - so these content-lists would actually move over to micro-layout. We don't have to call them content-lists if we think it might be confusing, we could just have it called a 1-up grid or something since they're just one-column, multi rows.

image

Also, that old lady avatar gets me everytime.

**Comment by gcstaublin** [comment]
I'm going to merge this.

Separating cards, avatars, etc seems like it can happen when cards are created, or when the non-image avatar variants are created?

**Pull request merged**
